### ISSUE TITLE
Failed assertion on boot on master of sitl_gazebo

### ISSUE THREAD

**Issue by LorenzMeier** [Dronecode/sitl_gazebo#20]
@ChristophTobler I get this when trying to run your opt flow version:

```
Assertion failed: (px != 0), function operator->, file /usr/local/include/boost/smart_ptr/shared_ptr.hpp, line 687.
```

Have you seen this one before?

**Comment by LorenzMeier** [comment]
This happens on trying to resolve an uninitialised pointer through the ```->``` operator.

**Comment by ChristophTobler** [comment]
No I have not...
Did you run "make posix_sitl_default gazebo_iris_opt_flow"?

**Comment by LorenzMeier** [comment]
It broke the default Iris model as well. Try running ```make posix gazebo```.

**Comment by ChristophTobler** [comment]
both still work for me. That's weird...

**Comment by ChristophTobler** [comment]
Was there another PR  in between?

**Comment by LorenzMeier** [comment]
I believe its due to this: https://github.com/PX4/sitl_gazebo/pull/4/files

@tumbili I believe your fixed wing mode is using uninitialized memory. Which is why things explode for you. The fixed wing model needs to be redone properly. Chances are good it will actually work then.

**Comment by LorenzMeier** [comment]
@julianoes I believe you fixed this one.

**Comment by julianoes** [comment]
I believe I only worked around it by never using the fixedwing model.

**Comment by tumbili** [comment]
@LorenzMeier I actually rebased on master and since then I get this message for the cessna simulation. When I'm using the old cessna gazebo branch I don't have any issues. Need to check what goes wrong there. But I can confirm the the error appears when you try to use a joint pointer which was never created.

**Comment by LorenzMeier** [comment]
Fixed!
