### ISSUE TITLE
no member named 'SetAngle' in 'gazebo::physics::Joint'

### ISSUE THREAD

**Issue by abencomo** [Dronecode/sitl_gazebo#25]
I'm not longer able to build the sitl_gazebo after updating to the latest codebase today.  I'm getting these errors:

[ 87%] Building CXX object CMakeFiles/rotors_gazebo_mavlink_interface.dir/src/gazebo_mavlink_interface.cpp.o
/Users/abencomo/git/Firmware/Tools/sitl_gazebo/src/gazebo_mavlink_interface.cpp:406:27: error: 
      no member named 'SetAngle' in 'gazebo::physics::Joint'
      left_elevon_joint_->SetAngle(0, roll);
      ~~~~~~~~~~~~~~~~~~  ^
/Users/abencomo/git/Firmware/Tools/sitl_gazebo/src/gazebo_mavlink_interface.cpp:407:28: error: 
      no member named 'SetAngle' in 'gazebo::physics::Joint'
      right_elevon_joint_->SetAngle(0, -roll);
      ~~~~~~~~~~~~~~~~~~~  ^
/Users/abencomo/git/Firmware/Tools/sitl_gazebo/src/gazebo_mavlink_interface.cpp:408:24: error: 
      no member named 'SetAngle' in 'gazebo::physics::Joint'
      elevator_joint_->SetAngle(0, -pitch);
      ~~~~~~~~~~~~~~~  ^
3 errors generated.
make[2]: *** [CMakeFiles/rotors_gazebo_mavlink_interface.dir/src/gazebo_mavlink_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_mavlink_interface.dir/all] Error 2
make: *** [all] Error 2

**Comment by LorenzMeier** [comment]
You might want to use the stable branch, which is currently used in PX4.

**Comment by abencomo** [comment]
Do you mean v1.1.2?

https://github.com/PX4/Firmware/tree/v1.1.2

**Comment by abencomo** [comment]
As you suggested, I used the stable branch:

git clone -b stable https://github.com/PX4/sitl_gazebo.git

However, I'm now getting this 'Eigen/Eigen' file not found error:
........
[ 76%] Building CXX object CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o
In file included from /Users/abencomo/git/Firmware/Tools/sitl_gazebo/src/gazebo_controller_interface.cpp:22:
/Users/abencomo/git/Firmware/Tools/sitl_gazebo/include/gazebo_controller_interface.h:23:10: fatal error: 
      'Eigen/Eigen' file not found
#include <Eigen/Eigen>
         ^
1 error generated.
make[2]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/all] Error 2
make: *** [all] Error 2

**Comment by ecmnet** [comment]
@abencomo Same happens to me. Do you solved that already?

**Comment by sx00** [comment]
same issue even in stable

**Comment by LorenzMeier** [comment]
Please try with the instructions here:
http://dev.px4.io/starting-installing-linux.html
and here:
http://dev.px4.io/simulation-gazebo.html

And let me know if that works or not.

**Comment by sx00** [comment]
I tried this (I'm using OSX 10.11.3):
http://dev.px4.io/starting-installing-mac.html
and then:
http://dev.px4.io/simulation-gazebo.html
```
cd ~/src/Firmware
make posix_sitl_default gazebo
```
and here I got a few errors with master or stable branch:

```
src/Firmware/Tools/sitl_gazebo/src/gazebo_opticalFlow_plugin.cpp:59:5: error: 
      no matching function for call to 'dynamic_pointer_cast'
    boost::dynamic_pointer_cast<sensors::CameraSensor>(_sensor);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
src/Firmware/Tools/sitl_gazebo/src/gazebo_opticalFlow_plugin.cpp:64:9: error: 
      no matching function for call to 'dynamic_pointer_cast'
    if (boost::dynamic_pointer_cast<sensors::DepthCameraSensor>(_sensor))
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
src/Firmware/Tools/sitl_gazebo/src/gazebo_lidar_plugin.cpp:63:5: error: 
      no matching function for call to 'dynamic_pointer_cast'
    boost::dynamic_pointer_cast<sensors::RaySensor>(_parent);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by nicolaerosia** [comment]
SetAngle has been replaced by SetPosition

**Comment by LorenzMeier** [comment]
Fixed, thanks!
