### ISSUE TITLE
libLiftDragPlugin.so plugin is not detected

### ISSUE THREAD

**Issue by CarlOlsson** [Dronecode/sitl_gazebo#28]
After installing the simulation environment [following the devguide](http://dev.px4.io/starting-installing-linux.html) I was missing the plugin libLiftDragPlugin.so.

It was solved by adding it to Firmware/Tools/sitl_gazebo/Build

It should also be possible to solve it by removing the *if* from: (thx @sanderux)
```if(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin")
add_library(LiftDragPlugin SHARED src/liftdrag_plugin/liftdrag_plugin.cpp)
target_link_libraries(LiftDragPlugin mav_msgs ${Boost_LIBRARIES} ${GAZEBO_LIBRA$
add_dependencies(LiftDragPlugin mav_msgs)
endif()```
in tools/sitl_gazebo/cmakelist.txt

**Comment by sanderux** [comment]
This issue should be raised in https://github.com/PX4/Firmware

**Comment by CarlOlsson** [comment]
moved issue to [https://github.com/PX4/Firmware](https://github.com/PX4/Firmware)
