### ISSUE TITLE
Accelerometer problem when vehicle is on ground

### ISSUE THREAD

**Issue by sverling** [Dronecode/sitl_gazebo#29]
We saw the problem, that when the vehicle is on the ground it continuously detects collisions which affect the IMU measurements (as seen in the picture). This can cause the estimator to diverge.

![px42](https://cloud.githubusercontent.com/assets/6067950/14713465/880e1d3a-07e1-11e6-94e7-b0920dd76934.png)

![px41](https://cloud.githubusercontent.com/assets/6067950/14713486/9d96a8ac-07e1-11e6-96e8-4aa9fb3901af.png)

**Comment by LorenzMeier** [comment]
@tfoote any chance to get John helping with this?

**Comment by LorenzMeier** [comment]
We fixed this on PX4 master.
